### ISSUE TITLE
Public data set - prompts

### ISSUE THREAD

**Issue by mgscox** [simple-bench/SimpleBench#1]
The public data set should not include the prompt, only the question and answer. Notably, for O1 and possibly others, the prompt may reduce the model's performance; ref. [Open AI Documentation - O1 - Advice on prompting](https://platform.openai.com/docs/guides/reasoning/advice-on-prompting#advice-on-prompting)

A suggestion would be to maintain a separate file with different system-prompts that can provide recommended (or at least currently best-performing) prompts. This might also provide options for 1-shot and multi-shot priming, etc.

**Comment by ayulockin** [comment]
This is addressed in the #4 PR. Do let me know if it's alright.

**Comment by simple-bench** [comment]
+1 to @ayulockin 

Note that we also share a csv without the system prompts: https://github.com/simple-bench/SimpleBench/blob/main/simple_bench_public_set.csv
