### ISSUE TITLE
Speed up evaluation using async

### ISSUE THREAD

**Issue by ayulockin** [simple-bench/SimpleBench#2]
If the authors are willing, I can speed up the evaluation pipeline by doing some asynchronous programming here. 

Weave evaluation uses async under the hood. 

This method can be made asynchronous as well: https://github.com/simple-bench/SimpleBench/blob/03e924076787fc48697a4e0bd0c9fe8c471b3eee/weave_utils/models.py#L62

**Comment by SmartManoj** [comment]
> If the authors are willing

Will they be against it?

**Comment by ayulockin** [comment]
Addressed in the #4 PR.
