### ISSUE TITLE
Is complete data not released?

### ISSUE THREAD

**Issue by kaswani29** [simple-bench/SimpleBench#6]
We only see 10 questions from the dataset released on the github?

**Comment by PiotrSss** [comment]
![CleanShot 2024-12-19 at 18 25 45@2x](https://github.com/user-attachments/assets/ffa43d2d-ef0c-4da9-982c-b1c40ca622ad)
https://drive.google.com/file/d/1mddNFK5UbBFVr3oDftd2Kyc6D8TFctfe/view
